project_id = "ddmimmbnuvcqlndkawar"

[functions.admin-create-users]
verify_jwt = false

[functions.update-crypto-data]
verify_jwt = false

[functions.calculate-crypto-probabilities]
verify_jwt = false
